trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - testdata/*


variables:
  artifactName: 'dvonna.Site'


stages:
- stage: 'Build'
  jobs:
  - template: .azure-pipelines/build.yml
    parameters:
      artifactName: '$(artifactName)'

- stage: 'Test'
  dependsOn: 'Build'
  jobs:
  - template: .azure-pipelines/deploy.yml
    parameters:
      artifactName: '$(artifactName)'
      siteName: 'dvonna-test'
      location: 'northeurope'
      environment: 'test'

- stage: 'Production'
  dependsOn: 'Test'
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: .azure-pipelines/deploy.yml
    parameters:
      artifactName: '$(artifactName)'
      siteName: 'dvonna'
