trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - testdata/*


variables:
  artifactName: 'dvonna.Site'


stages:
- stage: 'Build'
  jobs:
  - template: .azure-pipelines/build.yml
    parameters:
      artifactName: '$(artifactName)'

- stage: 'Test'
  dependsOn: 'Build'
  jobs:
  - template: .azure-pipelines/deploy.yml
    parameters:
      artifactName: '$(artifactName)'
      siteName: 'dvonna-test'
      location: 'westeurope'
      environment: 'test'
